[package]
name = "karger"
version = "0.1.0"
authors = ["ktakayama <kazuyuki.takayama@wealthnavi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13.0"
rand = "0.8.3"
threadpool = "1.8.1"
